version: 2

jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          docker-compose -f build/components-docker-compose.yml up -d
          make ci-test

  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
          make docker-push

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+(\.[0-9]+)?/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+(\.[0-9]+)?/

