version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.15.6
      - image: circleci/postgres:13.1
      - image: circleci/redis:6.0.9-alpine
      - image: rabbitmq:alpine

    steps:
      - checkout
      - run: make ci-test
