version: 2
jobs:
  build:
    docker:
      - image: golang:1.15.6-alpine

      - image: postgres:13.1-alpine
        environment:
          - POSTGRES_DB: id_db
          - POSTGRES_USER: id_user
          - POSTGRES_PASSWORD: id_password

      - image: redis:6.0.9-alpine

      - image: rabbitmq:alpine

    steps:
      - checkout
      - run: make ci-test
