version: 2

jobs:
  test:
    docker:
      - image: cimg/go:1.16.0
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose -f ../build/docker-compose.yml up -d
      - run: apk add --no-cache make build-base
      - run: make ci-test

  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
          make docker-push

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+(\.[0-9]+)?/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+(\.[0-9]+)?/

