version: 2
jobs:
  build:
    docker:
      - image: golang:1.15.6-alpine
      - image: postgres:13.1-alpine
      - image: redis:6.0.9-alpine
      - image: rabbitmq:alpine

    steps:
      - checkout
      - run: make ci-test
